version: 2.1

orbs:
  gradle: circleci/gradle@3.0.0

executors:
  openjdk:
    docker:
      - image: cimg/openjdk:17.0.7

jobs:
  run-test:
    steps:
      - setup_remote_docker
      - gradle/test:
          executor: openjdk
          deps_checksum_file: build.gradle.kts

# ジョブの実行順の指定
workflows:
  build_and_test:
    jobs:
      - run-test