version: 2.1

orbs:
  gradle: circleci/gradle@3.0.0

executors:
  openjdk:
    docker:
      - image: cimg/openjdk:17.0.7

jobs:
  test:
    steps:
      - setup_remote_docker
      - checkout
      - gradle/with_cache:
          cache_key: v1
          deps_checksum_file: build.gradle.kts
          steps:
            - run:
                command: ./gradlew test
                name: Run Tests
                working_directory: .
          wrapper_checksum_file: gradlew
      - collect_test_results:
          reports_path: build/reports/
          test_results_path: build/test-results/
# ジョブの実行順の指定
workflows:
  build_and_test:
    jobs:
      - run-test